/**
 * Script to generate tracking-plan.md from tracker.ts
 * Run with: pnpm generate:tracking-plan
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '..')

// Read the tracker file
const trackerPath = path.join(rootDir, 'src', 'lib', 'utils', 'tracker.ts')
const trackerContent = fs.readFileSync(trackerPath, 'utf-8')

// Extract events using regex
const eventRegex = /(\w+):\s*\{\s*description:\s*['"]([^'"]+)['"],\s*properties:\s*\{([^}]*)\}/g
const events: Array<{
  name: string
  description: string
  properties: Array<{ key: string; type: string; description: string; optional: boolean }>
}> = []

let match
while ((match = eventRegex.exec(trackerContent)) !== null) {
  const [, name, description, propertiesStr] = match

  // Parse properties
  const properties: Array<{ key: string; type: string; description: string; optional: boolean }> =
    []
  const propRegex = /(\w+):\s*['"]([^'"]+)['"]/g
  let propMatch
  while ((propMatch = propRegex.exec(propertiesStr)) !== null) {
    const [, key, value] = propMatch
    // Parse format: "type: description" or "type?: description"
    const colonIndex = value.indexOf(':')
    if (colonIndex > 0) {
      const typePart = value.substring(0, colonIndex).trim()
      const descPart = value.substring(colonIndex + 1).trim()
      const optional = typePart.endsWith('?')
      const type = optional ? typePart.slice(0, -1) : typePart
      properties.push({ key, type, description: descPart, optional })
    }
  }

  events.push({
    name,
    description,
    properties,
  })
}

// Generate markdown with simple table
const markdown = `# Tracking Plan

> **Auto-generated from** \`src/lib/utils/tracker.ts\`  
> **Last updated:** ${new Date().toISOString().split('T')[0]}

This document defines all analytics events for the Bidding App.

## Events

| Event Name | Description | Properties |
|------------|-------------|------------|
${events
  .map((event) => {
    const propsList = event.properties
      .map((p) => `\`${p.key}\`${p.optional ? '?' : ''}: ${p.type}`)
      .join('\u003cbr\u003e')
    return `| \`${event.name}\` | ${event.description} | ${propsList || '-'} |`
  })
  .join('\n')}

## Event Details

${events
  .map((event) => {
    return `### \`${event.name}\`

**Description:** ${event.description}

${event.properties.length > 0 ? '**Properties:**' : '*No properties*'}

${event.properties
  .map(
    (p) =>
      `- \`${p.key}\` (${p.type}${p.optional ? ', optional' : ''}): ${p.description}`
  )
  .join('\n')}
`
  })
  .join('\n')}

---

## Naming Conventions

We follow the **Object-Action** naming convention:
- \`object_action\` format
- Lowercase with underscores
- Be specific: use \`hero_cta_clicked\` not just \`cta_clicked\`

## Standard Properties

These properties are automatically included by most analytics providers:

| Property | Description |
|----------|-------------|
| \`timestamp\` | When the event occurred |
| \`user_id\` | Identified user (if logged in) |
| \`session_id\` | Current session identifier |
| \`page_url\` | Current page URL |
| \`user_agent\` | Browser/device info |

## Implementation

### Track an Event

\`\`\`typescript
import { track } from '@/lib/utils/tracker'

// Simple event
track('page_view', { path: '/collections' })

// Event with properties
track('bid_placed', {
  collection_id: 'uuid-here',
  bid_amount_cents: 50000,
  bid_amount_usd: 500
})
\`\`\`

### Use the Hook

\`\`\`typescript
import { useTracker } from '@/hooks/useTracker'

function BidForm() {
  const { track } = useTracker()
  
  const handleSubmit = () => {
    track('bid_placed', { collection_id: '123', bid_amount_cents: 1000 })
  }
}
\`\`\`

## Adding New Events

1. Add the event to \`TRACKING_EVENTS\` in \`src/lib/utils/tracker.ts\`
2. Run \`pnpm generate:tracking-plan\` to update this document
3. TypeScript will provide autocomplete for event names and properties

---

*Generated by scripts/generate-tracking-plan.ts*
`

// Write the file
const outputPath = path.join(rootDir, 'docs', 'tracking-plan.md')
fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, markdown.trim())

console.log(`✅ Tracking plan generated: ${outputPath}`)
console.log(`   Events: ${events.length}`)
